all: buf divzero fmt sleep stderr

buf:
	gcc -o buf buf.c

divzero:
	gcc -o divzero divzero.c

fmt:
	gcc -o fmt fmt.c

sleep:
	gcc -o sleep sleep.c

stderr:
	gcc -o stderr stderr.c

clean:
	rm -rf buf divzero fmt sleep stderr *~

