all: buf divzero fmt sleep stderr getopt getenv

buf:
	gcc -o buf buf.c

divzero:
	gcc -o divzero divzero.c

fmt:
	gcc -o fmt fmt.c

sleep:
	gcc -o sleep sleep.c

stderr:
	gcc -o stderr stderr.c

getopt:
	gcc -o getopt getopt.c

getenv:
	gcc -o getenv getenv.c

clean:
	rm -rf buf divzero fmt sleep stderr getenv getopt *~

