# Server notices
:compton.deathrow.net NOTICE * :*** Looking up your hostname...
:@@ NOTICE * :*** Looking up your hostname...
:compton.deathrow.net @@ * :*** Looking up your hostname...
:compton.deathrow.net NOTICE @@ :***Looking up your hostname...
:compton.deathrow.net NOTICE * :@@

# CAP reply
:@@ CAP * LS :account-notify extended-join identify-msg multi-prefix sasl
:compton.deathrow.net @@ * LS :account-notify extended-join identify-msg multi-prefix sasl
:compton.deathrow.net CAP @@ LS :account-notify extended-join identify-msg multi-prefix sasl
:compton.deathrow.net CAP * @@ :account-notify extended-join identify-msg multi-prefix sasl
:compton.deathrow.net CAP * LS :@@

# CAP ACK
:@@ CAP TupacSecure  ACK :multi-prefix
:compton.deathrow.net @@ TupacSecure  ACK :multi-prefix
:compton.deathrow.net CAP @@ ACK :multi-prefix
:compton.deathrow.net CAP TupacSecure @@ :multi-prefix
:compton.deathrow.net CAP TupacSecure ACK :@@


# Numeric
:compton.deathrow.net @@ TupacSecure :dummy

# Numeric 001
:@@ 001 TupacSecure :Welcome to the Thug Life
:compton.deathrow.net @@ TupacSecure :Welcome to the Thug Life
:compton.deathrow.net 001 @@ :Welcome to the Thug Life
:compton.deathrow.net 001 TupacSecure :@@

# Numeric 002
:@@ 002 TupacSecure :Your host is compton.deathrow.net[127.0.0.1/6667], running version thugpassion-1.0
:compton.deathrow.net 002 @@ :Your host is compton.deathrow.net[127.0.0.1/6667], running version thugpassion-1.0
:compton.deathrow.net 002 TupacSecure :@@
:compton.deathrow.net 002 TupacSecure :Your host is @@[127.0.0.1/6667], running version thugpassion-1.0
:compton.deathrow.net 002 TupacSecure :Your host is compton.deathrow.net[@@/6667], running version thugpassion-1.0
:compton.deathrow.net 002 TupacSecure :Your host is compton.deathrow.net[127.0.0.1/@@], running version thugpassion-1.0
:compton.deathrow.net 002 TupacSecure :Your host is compton.deathrow.net[127.0.0.1/6667], running version @@

# Numeric 003
:@@ 003 TupacSecure :This server was created Thu Jan 26 2017 at 20:12:59 UTC
:compton.deathrow.net 003 @@ :This server was created Thu Jan 26 2017 at 20:12:59 UTC
:compton.deathrow.net 003 TupacSecure :@@
:compton.deathrow.net 003 TupacSecure :This server was created @@ Jan 26 2017 at 20:12:59 UTC
:compton.deathrow.net 003 TupacSecure :This server was created Thu @@ 26 2017 at 20:12:59 UTC
:compton.deathrow.net 003 TupacSecure :This server was created Thu Jan @@ 2017 at 20:12:59 UTC
:compton.deathrow.net 003 TupacSecure :This server was created Thu Jan 26 @@ at 20:12:59 UTC
:compton.deathrow.net 003 TupacSecure :This server was created Thu Jan 26 2017 at @@:12:59 UTC
:compton.deathrow.net 003 TupacSecure :This server was created Thu Jan 26 2017 at 20:@@:59 UTC
:compton.deathrow.net 003 TupacSecure :This server was created Thu Jan 26 2017 at 20:12:@@ UTC
:compton.deathrow.net 003 TupacSecure :This server was created Thu Jan 26 2017 at 20:12:59 @@
:compton.deathrow.net 003 TupacSecure :This server was created Thu Jan 26 2017 at @@ UTC

# Numeric 004
:@@ 004 TupacSecure compton.deathrow.net thugpassion-01 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:compton.deathrow.net 004 @@ compton.deathrow.net thugpassion-01 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:compton.deathrow.net 004 TupacSecure @@ thugpassion-01 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:compton.deathrow.net 004 TupacSecure @@.deathrow.net thugpassion-01 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:compton.deathrow.net 004 TupacSecure compton.@@.net thugpassion-01 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:compton.deathrow.net 004 TupacSecure compton.deathrow.@@ thugpassion-01 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:compton.deathrow.net 004 TupacSecure compton.deathrow.net @@ DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:compton.deathrow.net 004 TupacSecure compton.deathrow.net thugpassion-01 @@ CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:compton.deathrow.net 004 TupacSecure compton.deathrow.net thugpassion-01 DOQRSZaghilopswz @@ bkloveqjfI
:compton.deathrow.net 004 TupacSecure compton.deathrow.net thugpassion-01 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz @@
:compton.deathrow.net 004 TupacSecure compton.deathrow.net @@
:compton.deathrow.net 004 TupacSecure @@

# Numeric 005
:@@ 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:@@.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.@@.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.@@ 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 @@ CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=@@ EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# @@ INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=@@ CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=@@,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,@,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,@@,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,@@ CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=@@:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:@@ PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=@@ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(@@)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@@ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=@@ MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=@@:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:@@ MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=@@ NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=@@ STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@@ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=@@ CASEMAPPING=rfc1459 :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=@@ :are supported by this server
:compton.deathrow.net 005 TupacSecure CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=deathrow STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :@@

# More Numeric 005
:compton.deathrow.net 005 TupacSecure CHARSET=@@ NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=@@ CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=@@ TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=@@ DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=@@ FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=@@:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:@@,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,@@:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:@@,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,@@:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:@@,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,@@:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:@@,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:@@,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,@@:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,@@:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:@@,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,@@:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:@@,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:@@,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR:@@ EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=@@,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,@@ CLIENTVER=3.0 SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=@@ SAFELIST ELIST=CTU KNOCK :are supported by this server
:compton.deathrow.net 005 TupacSecure CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=@@ KNOCK :are supported by this server


# Numeric 250
:@@ 250 TupacSecure :Highest connection count: 7369 (7368 clients) (1313830 connections received)
:compton.deathrow.net 250 @@ :Highest connection count: 7369 (7368 clients) (1313830 connections received)
:compton.deathrow.net 250 TupacSecure :@@
:compton.deathrow.net 250 TupacSecure :Highest connection count: @@ (7368 clients) (1313830 connections received)
:compton.deathrow.net 250 TupacSecure :Highest connection count: 7369 (@@ clients) (1313830 connections received)
:compton.deathrow.net 250 TupacSecure :Highest connection count: 7369 (7368 clients) (@@ connections received)

# Numeric 251
:compton.deathrow.net 251 @@ :There are 130 users and 84811 invisible on 27 servers
:@@ 251 TupacSecure :There are 130 users and 84811 invisible on 27 servers
:@@.deathrow.net 251 TupacSecure :There are 130 users and 84811 invisible on 27 servers
:compton.@@.net 251 TupacSecure :There are 130 users and 84811 invisible on 27 servers
:compton.deathrow.@@ 251 TupacSecure :There are 130 users and 84811 invisible on 27 servers
:compton.deathrow.net 251 TupacSecure :@@
:compton.deathrow.net 251 TupacSecure :There are @@ users and 84811 invisible on 27 servers
:compton.deathrow.net 251 TupacSecure :There are 130 users and @@ invisible on 27 servers
:compton.deathrow.net 251 TupacSecure :There are 130 users and 84811 invisible on @@ servers

# Numeric 252
:@@ 252 TupacSecure 30 :IRC Operators online
:compton.@@.net 252 TupacSecure 30 :IRC Operators online
:compton.deathrow.@@ 252 TupacSecure 30 :IRC Operators online
:compton.deathrow.net 252 @@ 30 :IRC Operators online
:compton.deathrow.net 252 TupacSecure @@ :IRC Operators online
:compton.deathrow.net 252 TupacSecure 30 :@@

# Numeric 253
:@@ 253 TupacSecure 39 :unknown connection(s)
:compton.@@.net 253 TupacSecure 39 :unknown connection(s)
:compton.deathrow.@@ 253 TupacSecure 39 :unknown connection(s)
:compton.deathrow.net @@ TupacSecure 39 :unknown connection(s)
:compton.deathrow.net 253 @@ 39 :unknown connection(s)
:compton.deathrow.net 253 TupacSecure @@ :unknown connection(s)
:compton.deathrow.net 253 TupacSecure 39 :@@

# Numeric 254
:@@ 254 TupacSecure 60332 :channels formed
:compton.deathrow.net 254 @@ 60332 :channels formed
:compton.deathrow.net 254 TupacSecure @@ :channels formed
:compton.deathrow.net 254 TupacSecure 60332 :@@

# Numeric 255
:@@ 255 TupacSecure :I have 5314 clients and 1 servers
:compton.deathrow.net 255 @@ :I have 5314 clients and 1 servers
:compton.deathrow.net 255 TupacSecure :I have @@ clients and 1 servers
:compton.deathrow.net 255 TupacSecure :I have 5314 clients and @@ servers
:compton.deathrow.net 255 TupacSecure :@@

# Numeric 265
:@@ 265 TupacSecure 5314 7368 :Current local users 5314, max 7368
:compton.deathrow.net 265 @@ 5314 7368 :Current local users 5314, max 7368
:compton.deathrow.net 265 TupacSecure @@ 7368 :Current local users 5314, max 7368
:compton.deathrow.net 265 TupacSecure 5314 @@ :Current local users 5314, max 7368
:compton.deathrow.net 265 TupacSecure 5314 7368 :@@
:compton.deathrow.net 265 TupacSecure 5314 7368 :Current local users @@, max 7368
:compton.deathrow.net 265 TupacSecure 5314 7368 :Current local users 5314, max @@

# Numeric 266
:@@ 266 TupacSecure 84941 97718 :Current global users 84941, max 97718
:compton.deathrow.net 266 @@ 84941 97718 :Current global users 84941, max 97718
:compton.deathrow.net 266 TupacSecure @@ 97718 :Current global users 84941, max 97718
:compton.deathrow.net 266 TupacSecure 84941 @@ :Current global users 84941, max 97718
:compton.deathrow.net 266 TupacSecure 84941 97718 :@@
:compton.deathrow.net 266 TupacSecure 84941 97718 :Current global users 84941, max @@
:compton.deathrow.net 266 TupacSecure 84941 97718 :Current global users @@, max 97718


# Numerics 375, 372, and 376 -- MOTD
:@@ 375 TupacSecure :- compton.deathrow.net Message of the Day -
:compton.deathrow.net 375 @@ :- compton.deathrow.net Message of the Day -
:compton.deathrow.net 375 TupacSecure :@@

:@@ 372 TupacSecure :- Welcome to compton.deathrow.net in California, USA.
:compton.deathrow.net 372 @@ :- Welcome to compton.deathrow.net in California, USA.
:compton.deathrow.net 372 TupacSecure :@@

:@@ 376 TupacSecure :End of /MOTD command.
:compton.deathrow.net 376 @@ :End of /MOTD command.
:compton.deathrow.net 376 TupacSecure :@@


# MODE to self
:@@ MODE TupacSecure :+i
:TupacSecure MODE @@ :+i
:TupacSecure MODE TupacSecure :@@
:TupacSecure MODE TupacSecure :+@@

# NOTICE
:@@ NOTICE TupacSecure :This nickname is registered. Please choose a different nickname, or identify via ./msg NickServ identify <password>..
:@@!NickServ@services. NOTICE TupacSecure :This nickname is registered. Please choose a different nickname, or identify via ./msg NickServ identify <password>..
:NickServ!@@@services. NOTICE TupacSecure :This nickname is registered. Please choose a different nickname, or identify via ./msg NickServ identify <password>..
:NickServ!NickServ@x@@ NOTICE TupacSecure :This nickname is registered. Please choose a different nickname, or identify via ./msg NickServ identify <password>..
:NickServ!NickServ@services. @ TupacSecure :This nickname is registered. Please choose a different nickname, or identify via ./msg NickServ identify <password>..
:NickServ!NickServ@services. NOTICE @@ :This nickname is registered. Please choose a different nickname, or identify via ./msg NickServ identify <password>..
:NickServ!NickServ@services. NOTICE TupacSecure :@@

# Numeric 302 -- USERINFO
:@@ 302 TupacSecure :suge*=+~suge@suge.deathrow.net 
:compton.deathrow.net 302 @@ :suge*=+~suge@suge.deathrow.net 
:compton.deathrow.net 302 TupacSecure :@@*=+~suge@suge.deathrow.net
:compton.deathrow.net 302 TupacSecure :@@=+~suge@suge.deathrow.net
:compton.deathrow.net 302 TupacSecure :suge@@=+~suge@suge.deathrow.net
:compton.deathrow.net 302 TupacSecure :suge@@+~suge@suge.deathrow.net
:compton.deathrow.net 302 TupacSecure :suge*=+@@@suge.deathrow.net
:compton.deathrow.net 302 TupacSecure :suge*=+~suge@x@@ 

# PONG
:@@ PONG compton.deathrow.net :compton.deathrow.net
:compton.deathrow.net PONG @@ :compton.deathrow.net
:compton.deathrow.net PONG compton.deathrow.net :@@

# WHOIS-related numerics
:@@ 311 TupacSecure TupacSecure ~pac thugpassion.deathrow.net * :Tupac Secure
:compton.deathrow.net 311 @@ TupacSecure ~pac thugpassion.deathrow.net * :Tupac Secure
:compton.deathrow.net 311 TupacSecure @@ ~pac thugpassion.deathrow.net * :Tupac Secure
:compton.deathrow.net 311 TupacSecure TupacSecure @@ thugpassion.deathrow.net * :Tupac Secure
:compton.deathrow.net 311 TupacSecure TupacSecure ~pac @@ * :Tupac Secure
:compton.deathrow.net 311 TupacSecure TupacSecure ~pac @@.deathrow.net * :Tupac Secure
:compton.deathrow.net 311 TupacSecure TupacSecure ~pac thugpassion.@@.net * :Tupac Secure
:compton.deathrow.net 311 TupacSecure TupacSecure ~pac thugpassion.deathrow.@@ * :Tupac Secure
:compton.deathrow.net 311 TupacSecure TupacSecure ~pac thugpassion.deathrow.net @@ :Tupac Secure
:compton.deathrow.net 311 TupacSecure TupacSecure ~pac thugpassion.deathrow.net * :@@

:@@ 319 TupacSecure TupacSecure :@#the-streets
:compton.deathrow.net 319 @@ TupacSecure :@#the-streets
:compton.deathrow.net 319 TupacSecure @@ :@#the-streets
:compton.deathrow.net 319 TupacSecure TupacSecure :@@

:@@ 312 TupacSecure TupacSecure compton.deathrow.net :Death Row
:compton.deathrow.net 312 @@ TupacSecure compton.deathrow.net :Death Row
:compton.deathrow.net 312 TupacSecure @@ compton.deathrow.net :Death Row
:compton.deathrow.net 312 TupacSecure TupacSecure @@ :Death Row
:compton.deathrow.net 312 TupacSecure TupacSecure compton.deathrow.net :@@
:compton.deathrow.net 312 TupacSecure TupacSecure @@.deathrow.net :Death Row
:compton.deathrow.net 312 TupacSecure TupacSecure compton.@@.net :Death Row
:compton.deathrow.net 312 TupacSecure TupacSecure compton.deathrow.@@ :Death Row

:@@ 379 TupacSecure TupacSecure :is using modes +i
:compton.deathrow.net 379 @@ TupacSecure :is using modes +i
:compton.deathrow.net 379 TupacSecure @@ :is using modes +i
:compton.deathrow.net 379 TupacSecure TupacSecure :@@
:compton.deathrow.net 379 TupacSecure TupacSecure :is using modes @@

:@@ 338 TupacSecure TupacSecure ~pac@thugpassion.deathrow.net 10.10.10.10 :Actual user@host, actual IP
:compton.deathrow.net 338 @@ TupacSecure ~pac@thugpassion.deathrow.net 10.10.10.10 :Actual user@host, actual IP
:compton.deathrow.net 338 TupacSecure @@ ~pac@thugpassion.deathrow.net 10.10.10.10 :Actual user@host, actual IP
:compton.deathrow.net 338 TupacSecure TupacSecure @@@thugpassion.deathrow.net 10.10.10.10 :Actual user@host, actual IP
:compton.deathrow.net 338 TupacSecure TupacSecure ~pac@x@@ 10.10.10.10 :Actual user@host, actual IP
:compton.deathrow.net 338 TupacSecure TupacSecure ~pac@thugpassion.deathrow.net @@ :Actual user@host, actual IP
:compton.deathrow.net 338 TupacSecure TupacSecure ~pac@thugpassion.deathrow.net @@.10.10.10 :Actual user@host, actual IP
:compton.deathrow.net 338 TupacSecure TupacSecure ~pac@thugpassion.deathrow.net 10.@@.10.10 :Actual user@host, actual IP
:compton.deathrow.net 338 TupacSecure TupacSecure ~pac@thugpassion.deathrow.net 10.10.@@.10 :Actual user@host, actual IP
:compton.deathrow.net 338 TupacSecure TupacSecure ~pac@thugpassion.deathrow.net 10.10.10.@@ :Actual user@host, actual IP
:compton.deathrow.net 338 TupacSecure TupacSecure ~pac@thugpassion.deathrow.net 10.10.10.10 :@@

:@@ 317 TupacSecure TupacSecure 111632 1497244610 :seconds idle, signon time
:compton.deathrow.net 317 @@ TupacSecure 111632 1497244610 :seconds idle, signon time
:compton.deathrow.net 317 TupacSecure @@ 111632 1497244610 :seconds idle, signon time
:compton.deathrow.net 317 TupacSecure TupacSecure @@ 1497244610 :seconds idle, signon time
:compton.deathrow.net 317 TupacSecure TupacSecure 111632 @@ :seconds idle, signon time
:compton.deathrow.net 317 TupacSecure TupacSecure 111632 1497244610 :@@

:@@ 318 TupacSecure TupacSecure :End of /WHOIS list.
:compton.deathrow.net 318 @@ TupacSecure :End of /WHOIS list.
:compton.deathrow.net 318 TupacSecure @@ :End of /WHOIS list.
:compton.deathrow.net 318 TupacSecure TupacSecure :@@

# Joining a channel
:@@!~tupac@thugpassion.deathrow.net JOIN :#badboy
:TupacSecure!@@@thugpassion.deathrow.net JOIN :#badboy
:TupacSecure!~tupac@@all@ JOIN :#badboy
:TupacSecure!~tupac@thugpassion.deathrow.net JOIN :@@

:@@ MODE #badboy +nt
:compton.deathrow.net MODE @@ +nt
:compton.deathrow.net MODE #badboy +@@
:compton.deathrow.net MODE #badboy @@
:compton.deathrow.net MODE #badboy -@@

# NAMES-related numerics
:@@ 353 TupacSecure = #badboy :TupacSecure biggie
:compton.deathrow.net 353 @@ = #badboy :TupacSecure biggie
:compton.deathrow.net 353 TupacSecure @@ #badboy :TupacSecure biggie
:compton.deathrow.net 353 TupacSecure = @@ :TupacSecure biggie
:compton.deathrow.net 353 TupacSecure = #badboy :@@

:@@ 366 TupacSecure #badboy :End of /NAMES list.
:compton.deathrow.net 366 @@ #badboy :End of /NAMES list.
:compton.deathrow.net 366 TupacSecure @@ :End of /NAMES list.
:compton.deathrow.net 366 TupacSecure #badboy :@@

# Numerics 324 and 329 -- Channel modes
:@@ 324 TupacSecure #badboy +nt
:compton.deathrow.net 324 @@ #badboy +nt
:compton.deathrow.net 324 TupacSecure @@ +nt
:compton.deathrow.net 324 TupacSecure #badboy @@
:compton.deathrow.net 324 TupacSecure #badboy +@@
:compton.deathrow.net 324 TupacSecure #badboy -@@

:@@ 329 TupacSecure #badboy 1497356470
:compton.deathrow.net 329 @@ #badboy 1497356470
:compton.deathrow.net 329 TupacSecure @@ 1497356470
:compton.deathrow.net 329 TupacSecure #badboy @@

# Numerics 367 and 368 -- Channel ban list
:@@ 367 TupacSecure #badboy nick!user@host.com biggie!~biggie@thugpassion.deathrow.net 1497356684
:compton.deathrow.net 367 @@ #badboy nick!user@host.com biggie!~biggie@thugpassion.deathrow.net 1497356684
:compton.deathrow.net 367 TupacSecure @@ nick!user@host.com biggie!~biggie@thugpassion.deathrow.net 1497356684
:compton.deathrow.net 367 TupacSecure #badboy @@!user@host.com biggie!~biggie@thugpassion.deathrow.net 1497356684
:compton.deathrow.net 367 TupacSecure #badboy nick!@all@@host.com biggie!~biggie@thugpassion.deathrow.net 1497356684
:compton.deathrow.net 367 TupacSecure #badboy nick!user@@all@ biggie!~biggie@thugpassion.deathrow.net 1497356684
:compton.deathrow.net 367 TupacSecure #badboy nick!user@host.com @@!~biggie@thugpassion.deathrow.net 1497356684
:compton.deathrow.net 367 TupacSecure #badboy nick!user@host.com biggie!@all@@thugpassion.deathrow.net 1497356684
:compton.deathrow.net 367 TupacSecure #badboy nick!user@host.com biggie!~biggie@@all@ 1497356684
:compton.deathrow.net 367 TupacSecure #badboy nick!user@host.com biggie!~biggie@thugpassion.deathrow.net @@

:@@ 368 TupacSecure #badboy :End of Channel Ban List
:compton.deathrow.net 368 @@ #badboy :End of Channel Ban List
:compton.deathrow.net 368 TupacSecure @@ :End of Channel Ban List
:compton.deathrow.net 368 TupacSecure #badboy :@@

# Numerics 352 and 315 -- WHO
:@@ 352 TupacSecure #badboy ~tupac thugpassion.deathrow.net compton.deathrow.net TupacSecure H@ :0 Tupac Secure
:compton.deathrow.net 352 @@ #badboy ~tupac thugpassion.deathrow.net compton.deathrow.net TupacSecure H@ :0 Tupac Secure
:compton.deathrow.net 352 TupacSecure @@ ~tupac thugpassion.deathrow.net compton.deathrow.net TupacSecure H@ :0 Tupac Secure
:compton.deathrow.net 352 TupacSecure #badboy @@ thugpassion.deathrow.net compton.deathrow.net TupacSecure H@ :0 Tupac Secure
:compton.deathrow.net 352 TupacSecure #badboy ~tupac @@ compton.deathrow.net TupacSecure H@ :0 Tupac Secure
:compton.deathrow.net 352 TupacSecure #badboy ~tupac @@.deathrow.net compton.deathrow.net TupacSecure H@ :0 Tupac Secure
:compton.deathrow.net 352 TupacSecure #badboy ~tupac thugpassion.@@.net compton.deathrow.net TupacSecure H@ :0 Tupac Secure
:compton.deathrow.net 352 TupacSecure #badboy ~tupac thugpassion.deathrow.@@ compton.deathrow.net TupacSecure H@ :0 Tupac Secure
:compton.deathrow.net 352 TupacSecure #badboy ~tupac thugpassion.deathrow.net @@ TupacSecure H@ :0 Tupac Secure
:compton.deathrow.net 352 TupacSecure #badboy ~tupac thugpassion.deathrow.net compton.deathrow.net @@ H@ :0 Tupac Secure
:compton.deathrow.net 352 TupacSecure #badboy ~tupac thugpassion.deathrow.net compton.deathrow.net TupacSecure @@ :0 Tupac Secure
:compton.deathrow.net 352 TupacSecure #badboy ~tupac thugpassion.deathrow.net compton.deathrow.net TupacSecure H@ :@@

:@@ 315 TupacSecure #badboy :End of /WHO list.
:compton.deathrow.net 315 @@ #badboy :End of /WHO list.
:compton.deathrow.net 315 TupacSecure @@ :End of /WHO list.
:compton.deathrow.net 315 TupacSecure #badboy :@@

# JOIN
:@@!~biggie@thugpassion.deathrow.net JOIN :#badboy
:biggie!@all@@thugpassion.deathrow.net JOIN :#badboy
:biggie!~biggie@@all@ JOIN :#badboy
:biggie!~biggie@thugpassion.deathrow.net JOIN :@@
:biggie!~biggie@@all@.deathrow.net JOIN :#badboy
:biggie!~biggie@thugpassion.@@.net JOIN :#badboy
:biggie!~biggie@thugpassion.deathrow.@@ JOIN :#badboy
:biggie!~biggie@thugpassion.deathrow.net JOIN :#@@

# PART
:@@!~tupac@thugpassion.deathrow.net PART #badboy
:TupacSecure!@all@@thugpassion.deathrow.net PART #badboy
:TupacSecure!~tupac@@all@ PART #badboy
:TupacSecure!~tupac@thugpassion.deathrow.net PART @@
:TupacSecure!~tupac@thugpassion.deathrow.net PART #@@
:TupacSecure!~tupac@thugpassion.deathrow.net PART #badboy :@@

# INVITE
:@@!~biggie@thugpassion.deathrow.net INVITE TupacSecure :#badboy
:biggie!@all@@thugpassion.deathrow.net INVITE TupacSecure :#badboy
:biggie!~biggie@@all@ INVITE TupacSecure :#badboy
:biggie!~biggie@thugpassion.@@.net INVITE TupacSecure :#badboy
:biggie!~biggie@thugpassion.deathrow.@@ INVITE TupacSecure :#badboy
:biggie!~biggie@thugpassion.deathrow.net INVITE @@ :#badboy
:biggie!~biggie@thugpassion.deathrow.net INVITE TupacSecure :@@

# TOPIC
:@@!~biggie@thugpassion.deathrow.net TOPIC #asdf :asdf
:biggie!@all@@thugpassion.deathrow.net TOPIC #asdf :asdf
:biggie!~biggie@@all@ TOPIC #asdf :asdf
:biggie!~biggie@thugpassion.deathrow.net TOPIC @@ :asdf
:biggie!~biggie@thugpassion.deathrow.net TOPIC #@@ :asdf
:biggie!~biggie@thugpassion.deathrow.net TOPIC #asdf :@@

# KICK
:@@!~biggie@thugpassion.deathrow.net KICK #badboy TupacSecure :#badboy
:biggie!@all@@thugpassion.deathrow.net KICK #badboy TupacSecure :#badboy
:biggie!~biggie@@all@ KICK #badboy TupacSecure :#badboy
:biggie!~biggie@thugpassion.deathrow.net KICK @@ TupacSecure :#badboy
:biggie!~biggie@thugpassion.deathrow.net KICK #@@ TupacSecure :#badboy
:biggie!~biggie@thugpassion.deathrow.net KICK #badboy @@ :#badboy
:biggie!~biggie@thugpassion.deathrow.net KICK #badboy TupacSecure :@@

# Numeric 404 -- cant send to channel
:@@ 404 TupacSecure #badboy :Cannot send to channel
:compton.deathrow.net 404 @@ #badboy :Cannot send to channel
:compton.deathrow.net 404 TupacSecure @@ :Cannot send to channel
:compton.deathrow.net 404 TupacSecure #@@ :Cannot send to channel
:compton.deathrow.net 404 TupacSecure #badboy :@@

# MODE for channel
:@@!~biggie@thugpassion.deathrow.net MODE #badboy -m
:biggie!@all@@thugpassion.deathrow.net MODE #badboy -m
:biggie!~biggie@@all@ MODE #badboy -m
:biggie!~biggie@thugpassion.@@.net MODE #badboy -m
:biggie!~biggie@thugpassion.deathrow.@@ MODE #badboy -m
:biggie!~biggie@thugpassion.deathrow.net MODE @@ -m
:biggie!~biggie@thugpassion.deathrow.net MODE #@@ -m
:biggie!~biggie@thugpassion.deathrow.net MODE #badboy @@
:biggie!~biggie@thugpassion.deathrow.net MODE #badboy -@@
:biggie!~biggie@thugpassion.deathrow.net MODE #badboy +@@

# NICK
:@@!~biggie@thugpassion.deathrow.net NICK :Biggie
:biggie!@all@@thugpassion.deathrow.net NICK :Biggie
:biggie!~biggie@@all@ NICK :Biggie
:biggie!~biggie@thugpassion.@@.net NICK :Biggie
:biggie!~biggie@thugpassion.deathrow.@@ NICK :Biggie
:biggie!~biggie@thugpassion.deathrow.net NICK :@@

# QUIT
:@@!~biggie@thugpassion.deathrow.net QUIT :Quit: asdf
:Biggie!@all@@thugpassion.deathrow.net QUIT :Quit: asdf
:Biggie!~biggie@@all@ QUIT :Quit: asdf
:Biggie!~biggie@thugpassion.deathrow.net QUIT :@@

# Numeric 482 -- not a channel operator
:@@ 482 TupacSecure #badboy :You are not channel operator
:compton.deathrow.net 482 @@ #badboy :You are not channel operator
:compton.deathrow.net 482 TupacSecure @@ :You are not channel operator
:compton.deathrow.net 482 TupacSecure #badboy :@@

# CTCP
:@@!~biggie@thugpassion.deathrow.net PRIVMSG TupacSecure :.PING.
:biggie!@all@@thugpassion.deathrow.net PRIVMSG TupacSecure :.PING.
:biggie!~biggie@@all@ PRIVMSG TupacSecure :.PING.
:biggie!~biggie@thugpassion.deathrow.net PRIVMSG @@ :.PING.
:biggie!~biggie@thugpassion.deathrow.net PRIVMSG TupacSecure :@@
:biggie!~biggie@thugpassion.deathrow.net PRIVMSG TupacSecure :.@@.
#:biggie!~biggie@thugpassion.deathrow.net PRIVMSG TupacSecure :.TIME.
#:biggie!~biggie@thugpassion.deathrow.net PRIVMSG TupacSecure :.VERSION.
:TupacSecure!~tupac@thugpassion.deathrow.net NOTICE TupacSecure :.VERSION @@.
:TupacSecure!~tupac@thugpassion.deathrow.net NOTICE TupacSecure :.TIME @@.
:TupacSecure!~tupac@thugpassion.deathrow.net NOTICE TupacSecure :.PING @@.
